# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a06ff814f8bbe2664c216a1ad27487ddd7337641fd19556858acd17764e82b8c409826fc98a987fe9b9b64cdb85503be5f9be546ea46762913831366419ac8cc

test:
  secret_key_base: b013a641a20fbe7f6f980500f2ed97698e88e942772c93785c647c87874adeb105bf61deec4ba106fd900b73a569fac8576ebeb15c7ea65f0e7c8c95e51c10c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
